sudo: required

services:
  - docker
  
before_install:
  - docker build -t docker_image .
  - docker save -o imgage_to_deploy docker_image
  - docker run -d -p 8080:8080 docker_image

script:
  - ls -al .
  - docker ps -a
  - docker images
  - netstat -tulnp
  - curl http://localhost:8080
